spring:
  application:
    name: job-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: trungnguyen
      password: admin
      authentication-database: admin
      database: job-service

server:
  port: 8081