version: '3.8'
services:
  mongodb-job:
    image: mongo:latest # use the latest image
    container_name: mongodb-job
    restart: unless-stopped
    environment: # set required env variables to access mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes: # optional to preserve database after container is deleted
      - ./database-data:/data/db
      - /etc/timezone:/ect/timezone:ro